# syntax=docker/dockerfile:1
FROM avstephen/marte2-sigtools-centos7:ayr

RUN echo "cd /opt/MARTe2/Projects/MARTe2-sigtools/bin && . setenv.sh" >> /root/.bashrc
RUN echo "cd /opt/MARTe2/Projects/MARTe2-sigtools/bin && . m2-completion.bash" >> /root/.bashrc
# Drop into a shell
CMD /bin/bash

