# syntax=docker/dockerfile:1
FROM centos:centos7 AS m2st_base

# Create a harmless exception for the set -u guards in the env scripts
ENV LD_LIBRARY_PATH=/root

# Check whether ENV variables are for the docker construction, or propagate into the default shell
ENV DOCKERHUB_IMAGE_NAME=avstephen/marte2-sigtools-centos7

# Minimal support from yum is we must have git, but tmux is handy.
RUN yum -y install git tmux

# Scripts should work robustly from any reasonable directory.
WORKDIR /opt/MARTe2/Projects

# Cache control use this with docker build --build-arg CACHE_DATE="$(date)" to force refresh.
ARG CACHE_DATE=1999-01-04

# All the build infrastructure is maintained with the project
#
RUN git clone -b ayr-fix https://github.com/AdamVStephen/MARTe2-sigtools

# Scripts should work robustly from any reasonable directory.
WORKDIR /opt/MARTe2/Projects/MARTe2-sigtools/bin

# Get some feedback to the log file as to what commit this actually gave us
RUN git log -1

# Build correct source files
RUN ./install-build.sh

# Set the working environment
RUN echo "cd /opt/MARTe2/Projects/MARTe2-sigtools/bin && . setenv.sh" >> /root/.bashrc
RUN echo "cd /opt/MARTe2/Projects/MARTe2-sigtools/bin && . m2-completion.bash" >> /root/.bashrc
# Drop into a shell
CMD /bin/bash

