FROM centos:centos7

# Add EPEL
RUN yum -y install epel-release && yum -y update

# Development package as a group
RUN yum -y groups install "Development Tools"
# Extras that are generally useful
RUN yum -y install wget cmake3 octave libxml libxml2-devel bc

# Configure cmake3 as cmake
RUN alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 20 --slave /usr/local/bin/ctest ctest /usr/bin/ctest3 --slave /usr/local/bin/cpack cpack /usr/bin/cpack3 --slave /usr/local/bin/ccmake ccmake /usr/bin/ccmake3 --family cmake

# Dependencies to build MARTe2 and EPICS
RUN yum -y install ncurses-devel readline-devel
# Python and Perl Parse utilities for open62541 (open source impleemntation of OPC UA based on IEC 62541)
RUN yum -y install python-dateutil python-six perl-ExtUtils-ParseXS
# MDSplus
RUN yum -y install http://www.mdsplus.org/dist/el7/stable/RPMS/noarch/mdsplus-repo-7.50-0.el7.noarch.rpm
RUN yum -y install mdsplus-kernel* mdsplus-java* mdsplus-python* mdsplus-devel*

# Workspace to download and compile code from source
WORKDIR /root/Projects

# MARTe core, components and Padova training demos
#
# Caveat : requires git with openssl TLS support; on other distros YMMV.   See dockerhub avstephen/u18-git-openssl for a fix.
#RUN git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2.git MARTe2-dev
#RUN git clone -b \#351_OPCUA https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-components.git

# MARTe2-sigtools which pulls in MARTe and MARTe2-components
RUN git clone --recursive -b develop https://github.com/AdamVStephen/MARTe2-sigtools

# MARTe2-demos-padova
RUN git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-demos-padova.git 

# EPICS R7.0.2
RUN git clone -b R7.0.2 --recursive https://github.com/epics-base/epics-base.git epics-base-7.0.2

# Open Source OPCUA 
RUN git clone -b 0.3 https://github.com/open62541/open62541.git

# Download SDN:

RUN wget https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-demos-padova/raw/develop/Other/SDN_1.0.12_nonCCS.tar.gz

RUN tar zxvf SDN_1.0.12_nonCCS.tar.gz

