FROM centos:centos7

# Development package as a group
RUN yum -y groups install "Development Tools"
# Extras that are generally useful
RUN yum -y install wget cmake3 octave libxml libxml2-devel bc

# Configure cmake3 as cmake
RUN alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 20 --slave /usr/local/bin/ctest ctest /usr/bin/ctest3 --slave /usr/local/bin/cpack cpack /usr/bin/cpack3 --slave /usr/local/bin/ccmake ccmake /usr/bin/ccmake3 --family cmake

# Dependencies to build MARTe2 and EPICS
RUN yum -y install ncurses-devel readline-devel
# Python and Perl Parse utilities for open62541 (open source impleemntation of OPC UA based on IEC 62541)
RUN yum -y install python-dateut il python-six perl-ExtUtils-ParseXS
# MDSplus
RUN yum -y install http://www.mdsplus.org/dist/el7/stable/RPMS/noarch/mdsplus-repo-7.50-0.el7.noarch.rpm
RUN yum -y install mdsplus-kernel* mdsplus-java* mdsplus-python* mdsplus-devel*

# Workspace to download and compile code from source
WORKDIR /root/Projects

# MARTe core, components and Padova training demos
#
# Caveat : requires git with openssl TLS support; on other distros YMMV.   See dockerhub avstephen/u18-git-openssl for a fix.
#RUN git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2.git MARTe2-dev
#RUN git clone -b \#351_OPCUA https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-components.git

# MARTe2-sigtools which pulls in MARTe and MARTe2-components
RUN git clone --recursive -b develop https://github.com/AdamVStephen/MARTe2-sigtools

# MARTe2-demos-padova
RUN git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-demos-padova.git 

# EPICS R7.0.2
RUN git clone -b R7.0.2 --recursive https://github.com/epics-base/epics-base.git epics-base-7.0.2

# Open Source OPCUA 
RUN git clone -b 0.3 https://github.com/open62541/open62541.git

# Download SDN:

RUN wget https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-demos-padova/raw/develop/Other/SDN_1.0.12_nonCCS.tar.gz

RUN tar zxvf SDN_1.0.12_nonCCS.tar.gz

# Build the open62541 library:

RUN mkdir ~/Projects/open62541/build && cd ~/Projects/open62541/build && cmake3 .. && make

# Compile SDN:

RUN cd ~/Projects/SDN_1.0.12_nonCCS && make

#Compiling EPICS
RUN cd epics-base-7.0.2 && echo "OP_SYS_CXXFLAGS += -std=c++11" >> configure/os/CONFIG_SITE.linux-x86_64.Common
RUN cd epics-base-7.0.2 && make

#Environment variables
ENV MARTe2_PROJECT_ROOT=/root/Projects/MARTe2-sigtools
ENV MARTe2_DIR=${MARTe2_PROJECT_ROOT}/MARTe2-dev
ENV MARTe2_Components_DIR=${MARTe2_PROJECT_ROOT}/MARTe2-components
ENV OPEN62541_LIB=/root/Projects/open62541/build/bin
ENV OPEN62541_INCLUDE=/root/Projects/open62541/build
ENV EPICS_BASE=/root/Projects/epics-base-7.0.2
ENV EPICSPVA=/root/Projects/epics-base-7.0.2
ENV EPICS_HOST_ARCH=linux-x86_64
ENV SDN_CORE_INCLUDE_DIR=/root/Projects/SDN_1.0.12_nonCCS/src/main/c++/include/
ENV SDN_CORE_LIBRARY_DIR=/root/Projects/SDN_1.0.12_nonCCS/target/lib/
ENV PATH=$PATH:/root/Projects/epics-base-7.0.2/bin/linux-x86_64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MARTe2_DIR/Build/x86-linux/Core/:$EPICS_BASE/lib/$EPICS_HOST_ARCH:$SDN_CORE_LIBRARY_DIR

# Build MARTe
ENV MDSPLUS_DIR=/usr/local/mdsplus

RUN cd ${MARTe2_PROJECT_ROOT}/MARTe2-dev && make -f Makefile.linux
RUN cd ${MARTe2_PROJECT_ROOT}/MARTe2-components && git checkout develop && make -f Makefile.linux
RUN cd /root/Projects/MARTe2-demos-padova && make -f Makefile.x86-linux






CMD /bin/bash






