# Check how to install tzdata which can be fiddly due to interactive checks.
FROM ubuntu:18.04 AS ub1804_base

#RUN yum -y update
RUN apt-get update

FROM ub1804_base AS ub1804_updated

#ARG INSTALL_CMD="yum -y install"
ARG INSTALL_CMD="apt-get install -y"

RUN $INSTALL_CMD tzdata

CMD /bin/bash
